# Generated by Django 4.2.7 on 2024-10-02 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_calculation_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 17, 25, 18, 552822, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productcalculation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productcalculation',
            unique_together={('product', 'calculation')},
        ),
    ]
