# Generated by Django 4.2.7 on 2024-10-06 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_productcalculation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcalculation',
            name='unique_productcalculation',
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 16, 23, 48, 41076, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterUniqueTogether(
            name='productcalculation',
            unique_together={('product', 'calculation')},
        ),
    ]
