# Generated by Django 4.2.7 on 2024-10-06 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_unit_unitorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 22, 18, 52, 89775, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='unitorder',
            name='value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
