# Generated by Django 4.2.7 on 2024-10-06 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_date_created_alter_unitorder_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 22, 19, 8, 701759, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
